[package]
name = "openhop-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "openhop"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
ctrlc = "3.5.2"
env_logger = "0.11.11"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
log = "0.4.34"
openhop-core = { path = "../core" }
