[package]
name = "openhop-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "openhop-app"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
openhop-core = { path = "../../crates/core" }
tauri = { version = "2", features = ["tray-icon", "macos-private-api"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
env_logger = "0.11"
parking_lot = "0.12"
ureq = { version = "3.4.2", features = ["json", "platform-verifier"] }
semver = "1.0.28"
anyhow = "1.0.104"
tauri-plugin-single-instance = "2"
