[package]
name = "openhop-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.104"
arboard = { version = "3.6.1", features = ["image-data"] }
bincode = "1"
blake2 = "0.11.0"
crossbeam-channel = "0.5.17"
dirs = "7.0.0"
log = "0.4.34"
parking_lot = "0.12.5"
png = "0.18.1"
serde = { version = "1.0.229", features = ["derive"] }
snow = { version = "0.10.0", default-features = false, features = ["default-resolver", "use-chacha20poly1305", "use-blake2", "use-curve25519", "use-getrandom"] }
socket2 = { version = "0.6.5", features = ["all"] }
thiserror = "2.0.21"
toml = "1.1.6"

[target.'cfg(target_os = "linux")'.dependencies]
evdev = "0.13.2"
x11rb = { version = "0.14.0", features = ["xtest", "xfixes", "xkb"] }

[target."cfg(windows)".dependencies]
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_System_LibraryLoader", "Win32_System_Threading", "Win32_UI_HiDpi", "Win32_Graphics_Gdi", "Win32_System_DataExchange"] }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10.1"
core-graphics = { version = "0.25.0", features = ["highsierra"] }
objc2-app-kit = { version = "0.3", default-features = false, features = ["std", "NSPasteboard"] }

[dev-dependencies]
env_logger = "0.11.11"
