[package]
name = "openhop-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.104"
arboard = { version = "3.6.1", features = ["image-data"] }
bincode = "1"
blake2 = "0.11.0"
crossbeam-channel = "0.5.17"
dirs = "7.0.0"
getrandom = "0.3"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp", "bmp", "tiff"] }
log = "0.4.34"
netdev = "0.46.3"
opener = { version = "0.9.0", features = ["reveal"] }
parking_lot = "0.12.5"
png = "0.18.1"
serde = { version = "1.0.229", features = ["derive"] }
snow = { version = "0.10.0", default-features = false, features = ["default-resolver", "use-chacha20poly1305", "use-blake2", "use-curve25519", "use-getrandom"] }
socket2 = { version = "0.6.5", features = ["all"] }
thiserror = "2.0.21"
toml = "1.1.6"

[target.'cfg(target_os = "linux")'.dependencies]
evdev = "0.13.2"
x11rb = { version = "0.14.0", features = ["xtest", "xfixes", "xkb", "composite", "xinput"] }

[target."cfg(windows)".dependencies]
windows-core = "0.62"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_System_LibraryLoader", "Win32_System_Threading", "Win32_UI_HiDpi", "Win32_Graphics_Gdi", "Win32_System_DataExchange", "Win32_System_Ole", "Win32_System_Com", "Win32_System_Com_StructuredStorage", "Win32_System_SystemServices", "Win32_UI_Shell", "Win32_UI_Shell_Common", "Win32_System_Memory", "Win32_System_SystemInformation", "Win32_Storage_Xps", "Win32_Graphics_Dwm", "Win32_System_Registry", "Win32_System_Power", "Win32_Media_Audio"] }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10.1"
core-graphics = { version = "0.25.0", features = ["highsierra"] }
objc2-app-kit = { version = "0.3", default-features = false, features = ["std", "NSPasteboard", "NSPasteboardItem", "NSRunningApplication", "libc"] }
objc2 = "0.6"
objc2-foundation = { version = "0.3", default-features = false, features = ["std", "NSString", "NSArray", "NSData", "NSURL"] }

[dev-dependencies]
env_logger = "0.11.11"
